name: Trixi.jl Nightly
on:
  schedule:
    # Every day at 16:00 GMT 
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run julia benchmark example
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - name: Instantiate benchmark
        run: |
          julia --project --color=yes -e '
            using Pkg;
            Pkg.add(url="https://github.com/trixi-framework/Trixi.jl", rev="main") # Replace with sources
            Pkg.instantiate()'
      - name: Run benchmark
        run: |
          julia --project --color=yes runbenchmark.jl
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: output.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          # alert-threshold: '200%'
          # comment-on-alert: true
          # fail-on-alert: true
          # alert-comment-cc-users: '@vchuravy'
      - name: Save Julia depot cache on cancel or failure
        id: julia-cache-save
        if: cancelled() || failure()
        uses: actions/cache/save@v4
        with: 
          path: |
            ${{ steps.julia-cache.outputs.cache-paths }}
          key: ${{ steps.julia-cache.outputs.cache-key }}
