name: Julia Example with BenchmarkTools.jl
on:
  schedule:
    # Every day at 16:00 GMT 
    - cron: "* 16 * * *"

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run julia benchmark example
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'trixi-framework/Trixi.jl'
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Build AirspeedVelocity
        env:
          JULIA_NUM_THREADS: 2
        run: |
          # Lightweight build step, as sometimes the runner runs out of memory:
          julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.add("AirspeedVelocity")'
          julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.build("AirspeedVelocity")'
      - name: Add ~/.julia/bin to PATH
        run: |
          echo "$HOME/.julia/bin" >> $GITHUB_PATH
      - name: Add 
        run: |
          julia -e 'import Pkg; Pkg.add(["OrdinaryDiffEqLowOrderRK", "OrdinaryDiffEqSSPRK"])'
      - name: Run benchmark
        run: |
          mkdir results
          benchpkg --rev="dirty" --script=benchmark/benchmarks.jl --output-dir=results/ --tune
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: results/output.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          # alert-threshold: '200%'
          # comment-on-alert: true
          # fail-on-alert: true
          # alert-comment-cc-users: '@vchuravy'
